name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: apt install libgtkmm-3.0 libwebkit2gtk-4.0 libvte-2.91
      
    - name: Compile
      run: make
